# https://youtu.be/a8N6_tzdSfE
name: Display_github_variables
run-name: Display github variables

on: 
  push:
    branches: main

jobs:
  default-env-variables:
    runs-on: ubuntu-latest
    steps:
      - name: 1 - Testing Secrets variables
        run: |
          echo "$DB_HOSTNAME"
        env:
          DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
      - name: 2 - Display Environment variables
        run: |
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"
          echo "HOME: ${HOME}"
          echo "GITHUB WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_API_URL ${GITHUB_API_URL}"
          echo "GITHUB_EVENT_PATH: ${GITHUB_EVENT_PATH}"
          echo "GITHUB_JOB: ${GITHUB_JOB}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "RUNNER_OS: ${RUNNER_OS}"
