name: pi_testdb
run-name: Test table elu
on:
  push:
    branches: main

jobs:
  play-sql:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Execute postgresql file
      run: |
        PGPASSWORD=$DB_PASSWORD psql -h $DB_HOSTNAME -d $DB_NAME -p $DB_PORT -U $DB_USER -f SQL/pi_sql_requests.sql
      env: 
        DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}   
