name: robin
run-name: Initialisation de la base de données robin
on:
  push:
    branches: main

jobs:
  show-data:
    runs-on: ubuntu-latest
    steps:
    # - name: Set up R
    #   uses: r-lib/actions/setup-r@v2
    # - name: Install packages
    #   uses: r-lib/actions/setup-r-dependencies@v2
    #   with:
    #     packages:
    #       any::RPostgres
    #       any::RPostgreSQL
    #       any::sf
    #       any::tidyverse

    # - name: Check out repository
    #   uses: actions/checkout@v3

    # - name: Show table in postgresql database
    #   run: Rscript -e 'source("show_pg_tables.R")'
    - name: Install postgresql client
      run: |
        sudo apt-get update
        sudo apt-get install postgresql-client
        PGPASSWORD=$DB_PASSWORD psql -h $DB_HOSTNAME -d $DB_NAME -p $DB_PORT -U $DB_USER -c "select count(*) from elu;"
      env: 
        DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}   

    

      
      
